{% set name = "apache-airflow-providers-oracle" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_oracle-{{ version }}.tar.gz
  sha256: 3df06a519f7da2d5ac01389cc8cb2d83c27a8322b09afb3b13f665283acd0224

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow-providers-common-sql >=1.20.0
    - apache-airflow >=2.9.0
    - oracledb >=2.0.0

test:
  imports:
    - airflow.providers.oracle
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-oracle for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/oracle/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-oracle/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
