{% set name = "apache-airflow-providers-oracle" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_oracle-{{ version }}.tar.gz
  sha256: f7977823260ae7f7b9211c57aafec96cba2332c2e589b0a5a6f8715879aa3a5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.9.0
    - apache-airflow-providers-common-sql >=1.20.0
    - oracledb >=2.0.0

test:
  imports:
    - airflow.providers.oracle
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-oracle for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/oracle/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-oracle/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
