context:
  name: apache-airflow-providers-oracle
  version: "4.5.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_oracle-${{ version }}.tar.gz
  sha256: 3d3c58a4f7f72bcab179f2a7dec9ae59d37f12d5191d6a875cd906e04ab75172

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.8.0
    - apache-airflow-providers-common-sql >=1.32.0
    - oracledb >=2.0.0

tests:
  - python:
      imports:
        - airflow.providers.oracle
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-oracle for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-oracle/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
